### ISSUE TITLE
Startsession.py - Indexerror

### ISSUE THREAD

**Issue by EugenSol** [DanielDuecker/RF_Localization#1]
`eugensolowjow@Eugens-MacBook-Pro:RF_Localization$python startsession.py 
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "startsession.py", line 12, in <module>
    rf_tools.analyse_measdata_from_file('measdata_2017_01_09.txt', txpos, txpos_offset, freqtx)
  File "/Users/eugensolowjow/RF_Localization/rf_tools.py", line 107, in analyse_measdata_from_file
    plotdata_line = np.concatenate((wp, mean, var), axis=1)
IndexError: axis 1 out of bounds [0, 1)`

**Comment by DanielDuecker** [comment]
solved
